url: "https://valentinhuber.me" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/"
title: "valentinhuber.me"
author: Valentin Huber
plugins:
  - jekyll-feed
defaults:
  - scope:
      path: "*"
    values:
      layout: "default"
      language: "english"
  - scope:
      path: "*/*"
      type: posts
    values:
      layout: "post"
      author:
        name: "Valentin Huber"
        picture: "/assets/valentin.jpeg"
